import { Criterion } from '@/types';

export const CATEGORIES = [
  { id: 1, name: 'Vị trí & Khả năng tiếp cận', icon: '📍' },
  { id: 2, name: 'Mặt bằng & Không gian', icon: '🏠' },
  { id: 3, name: 'Môi trường & Pháp lý', icon: '📋' },
  { id: 4, name: 'Tiềm năng & Chi phí', icon: '💰' },
];

export const CRITERIA: Criterion[] = [
  // === I. Vị trí & Khả năng tiếp cận ===
  {
    id: 1,
    name: 'Lưu lượng giao thông',
    description: 'Lượng người và phương tiện qua lại trong ngày',
    hint: 'Đứng quan sát tại vị trí khoảng 15-30 phút vào giờ cao điểm (7-9h sáng, 11-13h trưa, 17-19h chiều). Đếm số người đi bộ và xe qua lại.',
    category: 'Vị trí & Khả năng tiếp cận',
    categoryId: 1,
    options: [
      { score: 1, label: 'Rất thấp (hẻm cụt, đường vắng)' },
      { score: 2, label: 'Thấp (đường ít người qua lại)' },
      { score: 3, label: 'Trung bình (đường nhỏ, khu dân cư vừa phải)' },
      { score: 4, label: 'Cao (đường lớn, khu dân cư đông đúc)' },
      { score: 5, label: 'Rất cao (khu vực trung tâm, ngã tư lớn)' },
    ],
  },
  {
    id: 2,
    name: 'Khả năng hiển thị',
    description: 'Mức độ dễ nhìn thấy quán từ xa',
    hint: 'Đi bộ từ 2 hướng đường chính cách mặt bằng 50-100m. Có nhìn thấy rõ vị trí không? Có bị cây cối, biển hiệu khác che khuất không?',
    category: 'Vị trí & Khả năng tiếp cận',
    categoryId: 1,
    options: [
      { score: 1, label: 'Rất kém (khó nhìn thấy từ đường)' },
      { score: 2, label: 'Kém (bị che khuất bởi cây cối, công trình khác)' },
      { score: 3, label: 'Trung bình (cần đến gần mới nhìn rõ)' },
      { score: 4, label: 'Tốt (có thể nhìn thấy từ khoảng cách vừa phải)' },
      { score: 5, label: 'Xuất sắc (mặt tiền rộng, thoáng, không bị che khuất)' },
    ],
  },
  {
    id: 3,
    name: 'Tiện ích xung quanh',
    description: 'Sự hiện diện của các tiện ích phục vụ nhu cầu khách hàng',
    hint: 'Đi bộ vòng quanh bán kính 200-500m. Ghi nhận: trường học, văn phòng, chợ, siêu thị, bệnh viện, công viên, khu chung cư...',
    category: 'Vị trí & Khả năng tiếp cận',
    categoryId: 1,
    options: [
      { score: 1, label: 'Rất ít (khu vực vắng vẻ, ít tiện ích)' },
      { score: 2, label: 'Ít (chủ yếu là nhà ở)' },
      { score: 3, label: 'Trung bình (khu dân cư, một số cửa hàng nhỏ)' },
      { score: 4, label: 'Nhiều (cửa hàng tiện lợi, chợ, công viên...)' },
      { score: 5, label: 'Rất nhiều (trung tâm thương mại, văn phòng, trường học...)' },
    ],
  },
  {
    id: 4,
    name: 'Chỗ đậu xe',
    description: 'Khả năng đậu xe cho khách hàng',
    hint: 'Kiểm tra: có bãi giữ xe riêng không? Vỉa hè có rộng để xe máy không? Có bãi xe công cộng gần đó không? Đường có cấm đậu xe không?',
    category: 'Vị trí & Khả năng tiếp cận',
    categoryId: 1,
    options: [
      { score: 1, label: 'Không có chỗ đậu xe' },
      { score: 2, label: 'Rất ít chỗ đậu xe' },
      { score: 3, label: 'Khó khăn khi đậu xe' },
      { score: 4, label: 'Đủ chỗ đậu xe' },
      { score: 5, label: 'Rộng rãi, thuận tiện' },
    ],
  },
  {
    id: 5,
    name: 'Giao thông công cộng',
    description: 'Khả năng tiếp cận bằng phương tiện công cộng',
    hint: 'Tìm trạm xe buýt, ga metro gần nhất trên Google Maps. Trong bán kính 300m có trạm nào không? Có bao nhiêu tuyến đi qua?',
    category: 'Vị trí & Khả năng tiếp cận',
    categoryId: 1,
    options: [
      { score: 1, label: 'Rất không thuận tiện (cách xa trạm GTCC)' },
      { score: 2, label: 'Không thuận tiện (xa các trạm GTCC)' },
      { score: 3, label: 'Trung bình (phải đi bộ một đoạn đến trạm xe buýt)' },
      { score: 4, label: 'Thuận tiện (trong bán kính 500m có trạm xe buýt)' },
      { score: 5, label: 'Rất thuận tiện (gần trạm xe buýt, ga tàu)' },
    ],
  },

  // === II. Mặt bằng & Không gian ===
  {
    id: 6,
    name: 'Diện tích',
    description: 'Phù hợp với mô hình kinh doanh',
    hint: 'Phúc Tea cần tối thiểu 30m² cho mô hình take-away, 50-80m² cho quán ngồi. Đo hoặc ước lượng diện tích thực tế sử dụng được.',
    category: 'Mặt bằng & Không gian',
    categoryId: 2,
    options: [
      { score: 1, label: 'Rất nhỏ (không đủ diện tích)' },
      { score: 2, label: 'Nhỏ (hạn chế không gian)' },
      { score: 3, label: 'Trung bình (hơi chật hẹp)' },
      { score: 4, label: 'Phù hợp (đáp ứng nhu cầu cơ bản)' },
      { score: 5, label: 'Rất phù hợp (đủ rộng, thoải mái)' },
    ],
  },
  {
    id: 7,
    name: 'Hình dạng mặt bằng',
    description: 'Dễ dàng bố trí không gian kinh doanh',
    hint: 'Quan sát hình dạng: vuông hay dài hẹp? Có cột giữa, bậc thang, góc chết không? Tưởng tượng bố trí quầy bar, bàn ghế, kho.',
    category: 'Mặt bằng & Không gian',
    categoryId: 2,
    options: [
      { score: 1, label: 'Không gian bí bách, bất tiện' },
      { score: 2, label: 'Nhiều góc cạnh, cột, hạn chế không gian' },
      { score: 3, label: 'Mặt bằng méo, khó bố trí' },
      { score: 4, label: 'Chữ nhật, tương đối dễ bố trí' },
      { score: 5, label: 'Vuông vức, dễ bố trí' },
    ],
  },
  {
    id: 8,
    name: 'Mặt tiền',
    description: 'Độ rộng và khả năng thu hút của mặt tiền',
    hint: 'Đo bề ngang mặt tiền (mét). Dưới 3m là hẹp, 4-6m là tốt, trên 6m là rộng. Có thể đặt bảng hiệu lớn, trang trí nổi bật không?',
    category: 'Mặt bằng & Không gian',
    categoryId: 2,
    options: [
      { score: 1, label: 'Rất hẹp, khó thu hút khách' },
      { score: 2, label: 'Hẹp' },
      { score: 3, label: 'Bình thường' },
      { score: 4, label: 'Có thể tận dụng làm không gian ngoài trời' },
      { score: 5, label: 'Rộng rãi, thoáng đãng' },
    ],
  },
  {
    id: 9,
    name: 'Kết cấu & Tiện ích',
    description: 'Chất lượng kết cấu và tiện nghi sẵn có',
    hint: 'Kiểm tra: tường có nứt không? Trần có dột không? Hệ thống điện (đủ công suất cho máy xay, tủ lạnh?), nước, thoát nước, WC.',
    category: 'Mặt bằng & Không gian',
    categoryId: 2,
    options: [
      { score: 1, label: 'Xuống cấp nghiêm trọng' },
      { score: 2, label: 'Yếu kém, cần sửa chữa nhiều' },
      { score: 3, label: 'Trung bình, cần cải tạo' },
      { score: 4, label: 'Tương đối tốt, cần sửa chữa nhỏ' },
      { score: 5, label: 'Vững chắc, đầy đủ tiện nghi' },
    ],
  },
  {
    id: 10,
    name: 'Ánh sáng & Thông gió',
    description: 'Điều kiện ánh sáng và không khí',
    hint: 'Vào bên trong mặt bằng lúc ban ngày. Có ánh sáng tự nhiên không? Có cửa sổ, giếng trời? Không gian có bí, nóng, ẩm không?',
    category: 'Mặt bằng & Không gian',
    categoryId: 2,
    options: [
      { score: 1, label: 'Rất tối, bí, thiếu không khí' },
      { score: 2, label: 'Hơi tối, bí' },
      { score: 3, label: 'Trung bình' },
      { score: 4, label: 'Đủ ánh sáng, thông gió tốt' },
      { score: 5, label: 'Tự nhiên, thoáng mát' },
    ],
  },

  // === III. Môi trường & Pháp lý ===
  {
    id: 11,
    name: 'An ninh trật tự',
    description: 'Mức độ an toàn của khu vực',
    hint: 'Hỏi người dân xung quanh về tình hình an ninh. Quan sát: có camera an ninh khu vực không? Ban đêm có đèn đường không? Có tụ điểm phức tạp gần đó không?',
    category: 'Môi trường & Pháp lý',
    categoryId: 3,
    options: [
      { score: 1, label: 'Rất kém (khu vực phức tạp)' },
      { score: 2, label: 'Kém (có một số vấn đề về an ninh)' },
      { score: 3, label: 'Trung bình' },
      { score: 4, label: 'Tốt (an ninh đảm bảo)' },
      { score: 5, label: 'Rất tốt (khu vực an ninh, ít tệ nạn)' },
    ],
  },
  {
    id: 12,
    name: 'Vệ sinh môi trường',
    description: 'Điều kiện vệ sinh xung quanh',
    hint: 'Quan sát: có rác thải, nước đọng, mùi hôi xung quanh không? Hệ thống thoát nước có tốt không? Khu vực có bị ngập khi mưa không?',
    category: 'Môi trường & Pháp lý',
    categoryId: 3,
    options: [
      { score: 1, label: 'Rất ô nhiễm' },
      { score: 2, label: 'Ô nhiễm, nhiều rác thải' },
      { score: 3, label: 'Trung bình' },
      { score: 4, label: 'Tương đối sạch sẽ' },
      { score: 5, label: 'Sạch sẽ, thoáng mát' },
    ],
  },
  {
    id: 13,
    name: 'Cảnh quan xung quanh',
    description: 'Vẻ đẹp và cảnh quan khu vực',
    hint: 'Chụp ảnh cảnh quan xung quanh mặt bằng 360 độ. Có cây xanh, công viên không? Các công trình lân cận có đẹp, sạch sẽ không?',
    category: 'Môi trường & Pháp lý',
    categoryId: 3,
    options: [
      { score: 1, label: 'Rất xấu, gây khó chịu cho khách hàng' },
      { score: 2, label: 'Xấu, ảnh hưởng đến cảnh quan quán' },
      { score: 3, label: 'Bình thường' },
      { score: 4, label: 'Thoáng đãng' },
      { score: 5, label: 'Đẹp, có nhiều cây xanh' },
    ],
  },
  {
    id: 14,
    name: 'Giấy tờ pháp lý',
    description: 'Tình trạng giấy tờ pháp lý của mặt bằng',
    hint: 'Hỏi chủ nhà: có sổ đỏ/sổ hồng không? Giấy phép kinh doanh có được cấp cho loại hình F&B không? Có tranh chấp pháp lý nào không?',
    category: 'Môi trường & Pháp lý',
    categoryId: 3,
    options: [
      { score: 1, label: 'Không hợp lệ' },
      { score: 2, label: 'Không rõ ràng' },
      { score: 3, label: 'Thiếu một số giấy tờ quan trọng' },
      { score: 4, label: 'Hợp lệ, cần bổ sung một số giấy tờ' },
      { score: 5, label: 'Đầy đủ, hợp lệ' },
    ],
  },
  {
    id: 15,
    name: 'Chủ sở hữu',
    description: 'Mức độ uy tín và thiện chí của chủ nhà',
    hint: 'Đánh giá qua buổi gặp: chủ nhà có nhiệt tình không? Có lịch sử cho thuê tốt không? Có yêu cầu bất hợp lý không? Hỏi người thuê trước (nếu có).',
    category: 'Môi trường & Pháp lý',
    categoryId: 3,
    options: [
      { score: 1, label: 'Không đáng tin cậy' },
      { score: 2, label: 'Khó làm việc' },
      { score: 3, label: 'Trung bình' },
      { score: 4, label: 'Dễ dàng làm việc' },
      { score: 5, label: 'Uy tín, thiện chí' },
    ],
  },

  // === IV. Tiềm năng & Chi phí ===
  {
    id: 16,
    name: 'Giá thuê mặt bằng',
    description: 'Mức giá thuê so với thị trường',
    hint: 'So sánh giá thuê với các mặt bằng tương tự trong khu vực. Giá thuê nên chiếm không quá 15-20% doanh thu dự kiến hàng tháng.',
    category: 'Tiềm năng & Chi phí',
    categoryId: 4,
    options: [
      { score: 1, label: 'Rất cao' },
      { score: 2, label: 'Cao' },
      { score: 3, label: 'Trung bình' },
      { score: 4, label: 'Hợp lý' },
      { score: 5, label: 'Rất hợp lý' },
    ],
  },
  {
    id: 17,
    name: 'Tiềm năng phát triển',
    description: 'Khả năng phát triển của khu vực trong tương lai',
    hint: 'Quan sát: có công trình đang xây dựng không? Có bảng quy hoạch, dự án hạ tầng mới? Khu vực dân cư có đang mở rộng không?',
    category: 'Tiềm năng & Chi phí',
    categoryId: 4,
    options: [
      { score: 1, label: 'Rất thấp (khu vực có nguy cơ suy thoái)' },
      { score: 2, label: 'Thấp (khu vực đã ổn định)' },
      { score: 3, label: 'Trung bình' },
      { score: 4, label: 'Cao (có tiềm năng tăng trưởng)' },
      { score: 5, label: 'Rất cao (khu vực đang phát triển)' },
    ],
  },
  {
    id: 18,
    name: 'Khả năng cạnh tranh',
    description: 'Mức độ cạnh tranh trong khu vực',
    hint: 'Đi bộ trong bán kính 500m, đếm số quán trà sữa, cà phê, nước uống. Ghi lại tên và khoảng cách. Dùng phần ghi chú đối thủ ở trang trước.',
    category: 'Tiềm năng & Chi phí',
    categoryId: 4,
    options: [
      { score: 1, label: 'Rất nhiều đối thủ mạnh' },
      { score: 2, label: 'Cạnh tranh gay gắt' },
      { score: 3, label: 'Cạnh tranh trung bình' },
      { score: 4, label: 'Có thể tạo sự khác biệt' },
      { score: 5, label: 'Ít đối thủ cạnh tranh trực tiếp' },
    ],
  },
  {
    id: 19,
    name: 'Điều khoản hợp đồng',
    description: 'Mức độ thuận lợi của hợp đồng thuê',
    hint: 'Xem xét: thời hạn thuê (tối thiểu 3 năm), điều kiện tăng giá, tiền cọc, quyền chuyển nhượng, điều kiện chấm dứt hợp đồng.',
    category: 'Tiềm năng & Chi phí',
    categoryId: 4,
    options: [
      { score: 1, label: 'Rất bất lợi' },
      { score: 2, label: 'Không có lợi' },
      { score: 3, label: 'Thiếu rõ ràng' },
      { score: 4, label: 'Rõ ràng, bình thường' },
      { score: 5, label: 'Rõ ràng, có lợi' },
    ],
  },
  {
    id: 20,
    name: 'Linh hoạt kinh doanh',
    description: 'Khả năng thay đổi, cải tạo mặt bằng',
    hint: 'Hỏi chủ nhà: có cho phép đập tường, sơn lại, lắp bảng hiệu ngoài trời, sửa đổi mặt tiền không? Có giới hạn giờ kinh doanh không?',
    category: 'Tiềm năng & Chi phí',
    categoryId: 4,
    options: [
      { score: 1, label: 'Không cho phép thay đổi' },
      { score: 2, label: 'Khó thay đổi' },
      { score: 3, label: 'Ít linh hoạt' },
      { score: 4, label: 'Tương đối linh hoạt' },
      { score: 5, label: 'Cho phép thay đổi, sửa chữa' },
    ],
  },
];

export function getCriteriaByCategory(categoryId: number): Criterion[] {
  return CRITERIA.filter((c) => c.categoryId === categoryId);
}
